### ISSUE TITLE
 focusns-install 目录没有生成

### ISSUE THREAD

**Issue by wuliupo** [gavin-hu/focusns#1]
看了搭建开发环境：
https://github.com/gavin-hu/focusns/wiki/%E6%90%AD%E5%BB%BA%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83

> create database focusns
> 
> git clone https://github.com/gavin-hu/focusns.git
> cd focusns
> mvn install
> cd focusns-install
> java -jar focusns-install-[version].jar
> cd focusns-web
> mvn jetty:run

问一下 focusns-install 目录找不到，在哪里呢？

**Comment by 278883994** [comment]
------------------ 原始邮件 ------------------
发件人: "Pauli Wu"notifications@github.com;
发送时间: 2013年5月24日(星期五) 中午11:15
收件人: "gavin-hu/focusns"focusns@noreply.github.com; 

主题: [focusns]  focusns-install (#1)

看了搭建开发环境：
https://github.com/gavin-hu/focusns/wiki/%E6%90%AD%E5%BB%BA%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83

create database focusns

git clone https://github.com/gavin-hu/focusns.git
 cd focusns
 mvn install
 cd focusns-install
 java -jar focusns-install-[version].jar
 mvn jetty:run

问一下 focusns-install 目录找不到，在哪里呢？

**Comment by gavin-hu** [comment]
不好意思 文档需要重新更新了

**Comment by hb-chen** [comment]
我也在看呢！
直接run进去503 error

**Comment by gavin-hu** [comment]
文档已经更新，请参考 开发环境搭建 章节...
